version: '3'

services:
  rsshub:
    image: diygod/rsshub
    container_name: rsshub
    restart: unless-stopped
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535   
    ports:
        - 127.0.0.1:1200:1200
    environment:
        NODE_ENV: production
        CACHE_TYPE: memory
    networks:
     - nginx

networks:
  nginx:
    external: true

