version: "3"
services:
  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      #- CLI_ARGS= #optional
    volumes:
      - /opt/duplicati/config:/config
      - /opt/duplicati/backups:/backups
      - /var/lib/docker/volumes:/source
    ports:
      - 8200:8200
    restart: unless-stopped

    networks:
     - nginx

networks:
  nginx:
    external: true