version: '3'

services:
  searxng:
    image: searxng/searxng
    container_name: searxng
    restart: unless-stopped
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535   
    volumes:
      - /var/lib/docker/volumes/searxng/_data:/etc/searxng
    ports:
      - 127.0.0.1:18080:8080
    
    networks:
     - nginx
     - dragonflydb

networks:
  nginx:
    external: true
  dragonflydb:
    external: true