# the serialized access, or name of the access to use
access: 15M6fjnUPHBJnVt3KofVPkEHb8P9AbE48hP6135x3k9yFnHJkno7zkXCD44poevuBaGjYUjYH8fXrzyYdZHhDCizj9iryNh76bub3LvdezWELYj31iF6Xtsxd6YinijzfiNsMF6rinePqHQsNnsTVD78i1ze7FmCBaSXXfjAaQSQZr8yYaLHPmFD15fQjBBu5ZMThuTCYciHwMEX9fSw6gB49PeHKxYCmM7tmenqrSG1G6zK5kFns7C3pTLmy8VeRZrecKDzCX2y7YMtmRzEy3FxSXUNLZCFw

# if used in with -h, print advanced flags help
# advanced: false

# additional value appended to User-Agent
# client.additional-user-agent: ""

# User-Agent used for connecting to the satellite
# client.user-agent: ""

# address to listen on for debug endpoints
# debug.addr: 127.0.0.1:0

# If set, a path to write a process trace SVG to
# debug.trace-out: ""

# if true, log function filename and line number
# log.caller: false

# if true, set logging to development mode
# log.development: false

# configures log encoding. can either be 'console', 'json', 'pretty', or 'gcloudlogging'.
# log.encoding: ""

# the minimum log level to log
# log.level: info

# can be stdout, stderr, or a filename
# log.output: stderr

# if true, log stack traces
# log.stack: false

# address(es) to send telemetry to (comma-separated)
# metrics.addr: collectora.storj.io:9000

# application name for telemetry identification. Ignored for certain applications.
# metrics.app: gateway

# application suffix. Ignored for certain applications.
# metrics.app-suffix: -release

# address(es) to send telemetry to (comma-separated)
# metrics.event-addr: eventkitd.datasci.storj.io:9002

# instance id prefix
# metrics.instance-prefix: ""

# how frequently to send up telemetry. Ignored for certain applications.
# metrics.interval: 1m0s

# Minio Access Key to use
minio.access-key: jxdmo5qln476hayikzo7boa3qyda

# Minio generic server config path
# minio.dir: /home/admin/.local/share/storj/gateway/minio

# Minio Secret Key to use
minio.secret-key: j2ghd6jjypm22ndjfj7b3hybh7pvsbrep6jfpawmh7un3vbkubuty

# The default number of iterations for each check
# quickchecks: 100

# how many objects to delete in parallel with DeleteObjects
# s3.delete-objects-concurrency: 100

# return 501 (Not Implemented) for CopyObject calls
# s3.disable-copy-object: false

# make ListObjects(V2) fully S3-compatible (specifically: always return lexicographically ordered results) but slow
# s3.fully-compatible-listing: false

# include custom metadata in S3's ListObjects, ListObjectsV2 and ListMultipartUploads responses
# s3.include-custom-metadata-listing: true

# maximum number of items to list for gateway-side filtering using arbitrary delimiter/prefix
# s3.max-keys-exhaustive-limit: 100000

# MaxKeys parameter limit for S3's ListObjects and ListObjectsV2 responses
# s3.max-keys-limit: 1000

# MaxUploads parameter limit for S3's ListMultipartUploads responses
# s3.max-uploads-limit: 1000

# minimum part size for multipart uploads
# s3.min-part-size: 5242880

# address to serve S3 api over
# server.address: 127.0.0.1:7777

# address for jaeger agent
# tracing.agent-addr: agent.tracing.datasci.storj.io:5775

# application name for tracing identification
# tracing.app: gateway

# application suffix
# tracing.app-suffix: -release

# buffer size for collector batch packet size
# tracing.buffer-size: 0

# whether tracing collector is enabled
tracing.enabled: true

# how frequently to flush traces to tracing agent
tracing.interval: 30s

# buffer size for collector queue size
# tracing.queue-size: 0

# how frequent to sample traces
tracing.sample: 0.1

# serve content as a static website
website: true
