version: '3'

services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    restart: unless-stopped
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    volumes:
      - /var/lib/docker/volumes/postgres/_data:/var/lib/postgresql/data
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
    environment:
      #- POSTGRES_PASSWORD=xxxxxxxxxxxxxxxxxxx
      #- POSTGRES_USER=postgres
      #- TZ=Asia/Shanghai
    ports:
      - 127.0.0.1:5432:5432

    networks:
      - postgres

networks:
  postgres:
    external: true
