version: "3.9"
services:
  coder:
    container_name: coder
    image: ghcr.io/coder/coder
    ports:
      - "7080:7080"
    environment:
      CODER_PG_CONNECTION_URL: "postgresql://coder:2424dsgn6LJrQNaAtPy3R@postgres:5432/coder?sslmode=disable"
      CODER_HTTP_ADDRESS: "0.0.0.0:7080"
      CODER_ACCESS_URL: "http://193.24.209.140:7080"
    # If the coder user does not have write permissions on
    # the docker socket, you can uncomment the following
    # lines and set the group ID to one that has write
    # permissions on the docker socket.
    group_add:
      - "994" # docker group on host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
     - postgres

networks:
  postgres:
    external: true